services:
  private:
    image: postgres:15
    container_name: eHealth_Insights_postgres_private
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: private_eHealth_Insights
    ports:
      - "5432:5432"
    volumes:
      - postgres_private:/var/lib/postgresql/data
      - ./db-init/private/:/docker-entrypoint-initdb.d

  hospital1:
    image: postgres:15
    container_name: eHealth_Insights_postgres_hospital1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital1_eHealth_Insights
    ports:
      - "5433:5432"
    volumes:
      - postgres_hospital1:/var/lib/postgresql/data
      - ./db-init/hospital1/:/docker-entrypoint-initdb.d

  hospital2:
    image: postgres:15
    container_name: eHealth_Insights_postgres_hospital2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital2_eHealth_Insights
    ports:
      - "5434:5432"
    volumes:
      - postgres_hospital2:/var/lib/postgresql/data
      - ./db-init/hospital2/:/docker-entrypoint-initdb.d

volumes:
  postgres_private:
  postgres_hospital1:
  postgres_hospital2:
