services:
  vocab:
    image: postgres:15
    container_name: eHealth_Insights_postgres_vocab
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vocab_eHealth_Insights
    ports:
      - "5435:5432"
    volumes:
      - postgres_vocab:/var/lib/postgresql/data
      - ./db_setup/vocab/:/docker-entrypoint-initdb.d/

  private:
    image: postgres:15
    container_name: eHealth_Insights_postgres_private
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: private_eHealth_Insights
    ports:
      - "5432:5432"
    volumes:
      - postgres_private:/var/lib/postgresql/data
      - ./db_setup/private/:/docker-entrypoint-initdb.d
    depends_on:
      - hospital1
      - hospital2
      - vocab

  hospital1:
    image: postgres:15
    container_name: eHealth_Insights_postgres_hospital1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hospital1_eHealth_Insights
    ports:
      - "5433:5432"
    volumes:
      - postgres_hospital1:/var/lib/postgresql/data
      - ./db_setup/clinical/:/docker-entrypoint-initdb.d/
      - ./patient_data/hospital1/1_persons.sql:/docker-entrypoint-initdb.d/16_persons.sql
      - ./patient_data/hospital1/2_conditions.sql:/docker-entrypoint-initdb.d/17_conditions.sql
      - ./patient_data/hospital1/3_drugs.sql:/docker-entrypoint-initdb.d/18_drugs.sql
      - ./patient_data/hospital1/4_visits.sql:/docker-entrypoint-initdb.d/19_visits.sql
      - ./patient_data/hospital1/5_observations.sql:/docker-entrypoint-initdb.d/20_observations.sql
    depends_on:
      - vocab

  hospital2:
    image: postgres:15
    container_name: eHealth_Insights_postgres_hospital2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hospital2_eHealth_Insights
    ports:
      - "5434:5432"
    volumes:
      - postgres_hospital2:/var/lib/postgresql/data
      - ./db_setup/clinical/:/docker-entrypoint-initdb.d/
      - ./patient_data/hospital2/1_persons.sql:/docker-entrypoint-initdb.d/16_persons.sql
      - ./patient_data/hospital2/2_conditions.sql:/docker-entrypoint-initdb.d/17_conditions.sql
      - ./patient_data/hospital2/3_drugs.sql:/docker-entrypoint-initdb.d/18_drugs.sql
      - ./patient_data/hospital2/4_visits.sql:/docker-entrypoint-initdb.d/19_visits.sql
      - ./patient_data/hospital2/5_observations.sql:/docker-entrypoint-initdb.d/20_observations.sql
    depends_on:
      - vocab

volumes:
  postgres_private:
  postgres_hospital1:
  postgres_hospital2:
  postgres_vocab: