server.port=8080

# Private Database (User-related data)
private.datasource.url=${PRIVATE_DB_URL:jdbc:postgresql://private:5432/private_eHealth_Insights}
private.datasource.username=${POSTGRES_USER:postgres}
private.datasource.password=${POSTGRES_PASSWORD:password}
private.datasource.driver-class-name=org.postgresql.Driver

# Hospital 1 Database
hospital1.datasource.url=${HOSPITAL1_DB_URL:jdbc:postgresql://hospital1:5432/hospital1_eHealth_Insights}
hospital1.datasource.username=${POSTGRES_USER:postgres}
hospital1.datasource.password=${POSTGRES_PASSWORD:password}
hospital1.datasource.driver-class-name=org.postgresql.Driver

# Hospital 2 Database
hospital2.datasource.url=${HOSPITAL2_DB_URL:jdbc:postgresql://hospital2:5432/hospital2_eHealth_Insights}
hospital2.datasource.username=${POSTGRES_USER:postgres}
hospital2.datasource.password=${POSTGRES_PASSWORD:password}
hospital2.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none