name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Backend
        run: mvn -f backend/pom.xml clean package

      - name: Run Tests
        run: mvn -f backend/pom.xml test

  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: react-app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('react-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install
        working-directory: react-app

      - name: Build Frontend
        run: npm run build
        working-directory: react-app

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Backend
        run: |
          echo "Deploying backend..."
          java -jar backend/target/demo-0.0.1-SNAPSHOT.jar

      - name: Deploy Frontend
        run: |
          echo "Deploying frontend..."
          npx serve -s react-app/dist
